name: Update Jenkins plugins
on:
  workflow_dispatch:

jobs:
  update-jenkins-plugins:
    name: Update Jenkins Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update Jenkins plugins
        uses: ./.github/actions/jenkins-plugins-updater
        with:
          file: test/plugins.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Jenkins plugins auto-update
          body: Jenkins plugins update by BTD
          commit-message: Jenkins-plugins auto-update
          delete-branch: true
