name: Update Jenkins plugins
on:
  workflow_dispatch:

jobs:
  update-jenkins-plugins:
    name: Update Jenkins Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update Jenkins plugins Lint Code Base
        uses: ./.github/actions/jenkins-plugins-updater
